### ISSUE TITLE
[BUG] AttributeError: 'Namespace' object has no attribute 'no_compress'

### ISSUE THREAD

**Issue by philbudden** [eupnea-linux/depthboot-builder#36]
**Describe the bug**
Running `git clone --depth=1 https://github.com/eupnea-linux/depthboot-builder; cd depthboot-builder; ./main.py` returns an error:
```
Traceback (most recent call last):
    File "<path to home directory>/depthboot-builder/main.py", line 108, in <module>
      if args.no_compress:
AttributeError: 'Namespace' object has no attribute 'no_compress'
```

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/depthboot-builder; cd depthboot-builder; ./main.py``

**Full log**

Verbose log:
```
Installing: vboot, cgpt
Packages already installed, skipping
Installing: vboot, cgpt
Packages already installed, skipping
Verbosity increased
Traceback (most recent call last):
  File "<path to home directory>/depthboot-builder/./main.py", line 108, in <module>
    if args.no_compress:
AttributeError: 'Namespace' object has no attribute 'no_compress'
```

**Build system (please complete the following information):**
Tried on three systems:
 - OS: Fedora 36 Silverblue
 - OS: Ubuntu 22.04
 - OS: Chrome OS via Crostini (after following the additional Crostini instructions)

**Additional context**
I've ensured my Python version is >3.10 on all three systems and I've tried running with the `--no-shrink` flag.

**Comment by philbudden** [comment]
Discussed with main dev on Discord and a fix had already been deployed. Recloning the repo fixed the issue for me.
