### ISSUE TITLE
Script fails to format drive, errors out and fails

### ISSUE THREAD

**Issue by Inderix** [eupnea-linux/depthboot-builder#46]
Build/Target device:
HP Chromebook 14a - 4GB RAM, 32GB eMMC, GLK-R Intel Celeron N4020
ChromeOS version 110.0.5464.0
Debian bullseye crouton environment, Python 3.11 venv

Command line output

```
(venv) (bullseye)inderix@localhost:~$ git clone --depth=1 https://github.com/eupnea-linux/depthboot-builder && cd depthboot-builder && ./main.py
Cloning into 'depthboot-builder'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 53 (delta 8), reused 24 (delta 2), pack-reused 0
Receiving objects: 100% (53/53), 50.07 KiB | 2.28 MiB/s, done.
Resolving deltas: 100% (8/8), done.
Dependencies already installed, skipping
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux USB-drive/SD-card/image.
The script will now ask a few questions.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
   Pop!_OS (recommended)
   Ubuntu 
   Fedora 
   Debian 
 > Arch 
arch latest selected
Which desktop environment (Desktop GUI) would you like to use?
 > Gnome (recommended)
   KDE (recommended)
   Xfce (recommended for weak devices)
   LXQt (recommended for weak devices)
   cli (no desktop environment)
   deepin 
Gnome selected
Enter a username for the new user
Username (default: 'localuser'): inderix
Using inderix as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > stable (default, recommended)
   experimental 
   mainline (recommended)
stable kernel selected
Available devices: 
Select USB-drive/SD-card name or 'image' to build an image
 > sda           PSSD_T7 465.8G usb
   image Build image instead of writing to USB/SD-card directly
Writing directly to sda
User input complete
Starting build
Cleaning + preparing host system
Failed to remove /tmp/depthboot-build with python, using bash
Creating mount points
umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Downloading stable 5.10 kernel
Getting kernel version
Kernel files downloaded successfully
Downloading latest arch rootfs from geo.mirror.pkgbuild.com
Downloading: 173mb / 173mb
Downloading chromeos firmware
Cloning into '/tmp/depthboot-build/firmware'...
remote: Finding sources: 100% (1403/1403)
remote: Total 1403 (delta 358), reused 1146 (delta 358)
Receiving objects: 100% (1403/1403), 94.05 MiB | 531.00 KiB/s, done.
Resolving deltas: 100% (358/358), done.
Updating files: 100% (1405/1405), done.
Preparing USB/SD-card
umount: /dev/sda: not mounted.
umount: /dev/sda1: not mounted.
umount: /dev/sda2: not mounted.
Preparing device/image partition
Warning: The resulting partition is not properly aligned for best performance: 2048s % 65535s != 0s
Warning: The resulting partition is not properly aligned for best performance: 133120s % 65535s != 0s
Warning: The resulting partition is not properly aligned for best performance: 264192s % 65535s != 0s
Flashing kernel to device/image
33488+0 records in
33488+0 records out
17145856 bytes (17 MB, 16 MiB) copied, 0.892943 s, 19.2 MB/s
33488+0 records in
33488+0 records out
17145856 bytes (17 MB, 16 MiB) copied, 0.907956 s, 18.9 MB/s
Formatting rootfs part
mke2fs 1.46.2 (28-Feb-2021)
Found a dos partition table in /dev/sda3
/dev/sda3 is mounted; will not make a filesystem here!
Traceback (most recent call last):
  File "/home/inderix/depthboot-builder/./main.py", line 140, in <module>
    build.start_build(verbose=args.verbose, local_path=args.local_path, kernel_type=user_input["kernel_type"],
  File "/home/inderix/depthboot-builder/build.py", line 451, in start_build
    output_temp = prepare_usb_sd(build_options["device"], build_options["distro_name"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inderix/depthboot-builder/build.py", line 165, in prepare_usb_sd
    return partition_and_flash_kernel(device, True, distro_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inderix/depthboot-builder/build.py", line 212, in partition_and_flash_kernel
    bash(f"yes 2>/dev/null | mkfs.ext4 {rootfs_mnt}")  # 2>/dev/null is to supress yes broken pipe warning
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inderix/depthboot-builder/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 465, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'yes 2>/dev/null | mkfs.ext4 /dev/sda3' returned non-zero exit status 1.
(venv) (bullseye)inderix@localhost:~/depthboot-builder$
```

The drive itself was started as being formatted to exFAT by ChromeOS with only one partition, the script manages to create 2 partitions before seemingly failing to create/mount the 3rd.

**Comment by Apacelus** [comment]
Run these commands manually (replace "X" with your device's letter):
```
umount -lf /dev/sdX*
wipefs -af /dev/sdX
parted -s /dev/sdX mklabel gpt
parted -s -a optimal /dev/sdX unit mib mkpart Kernel 1 65
parted -s -a optimal /dev/sdX unit mib mkpart Kernel 65 129
parted -s -a optimal /dev/sdX unit mib mkpart Root 129 100%
mkfs.ext4 /dev/sdX3
mount /dev/sdX3 /mnt/depthboot
```

Do you get any errors?

**Comment by Inderix** [comment]
``mkfs.ext4 /dev/sdX3`` causes the following output:
```
(bullseye)root@localhost:/home/inderix/depthboot-builder# mkfs.ext4 /dev/sda3
mke2fs 1.46.2 (28-Feb-2021)
/dev/sda3 contains a exfat file system labelled 'UNTITLED'
Proceed anyway? (y,N) y
/dev/sda3 is mounted; will not make a filesystem here!
```
Executing the ``mount`` command results in an unknown fs error for exfat, which further confirms that it failed to format to ext4.

**Comment by Apacelus** [comment]
I suppose you have tried unplugging and replugging the drive?

Have you tried building an image and flashing it instead of using direct write?

**Comment by Inderix** [comment]
I have disconnected and re-connected the drive every re-run of the script, alongside removing the entire ``depthboot-builder`` directory and re-downloading it. I have just powerwashed ChromeOS and going to test if using the script on version 108.0.5359.172

**Comment by WeirdTreeThing** [comment]
Try running `umount /dev/sda*` about 5 times before running the script.

**Comment by Apacelus** [comment]
@Inderix what about building an image and writing it to the drive?

**Comment by Inderix** [comment]
Hey, sorry for the late response. To eliminate any and all variables, I've done a wipe of ChromeOS, completely reformatted the target drive, and am currently rebuilding my Crouton environment with a freshly built copy of Python 3.11. I'll report back if none of that resolves the problem.

**Comment by Inderix** [comment]
> Try running `umount /dev/sda*` about 5 times before running the script.

Tried this, alongside reformatting the drive, no luck



> @Inderix what about building an image and writing it to the drive?

Returns with this:
```
(venv) (bullseye)inderix@localhost:~$ git clone --depth=1 https://github.com/eupnea-linux/depthboot-builder && cd depthboot-builder && ./main.py
Cloning into 'depthboot-builder'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 53 (delta 8), reused 25 (delta 2), pack-reused 0
Receiving objects: 100% (53/53), 50.52 KiB | 3.89 MiB/s, done.
Resolving deltas: 100% (8/8), done.
[sudo] password for inderix: 
Dependencies already installed, skipping
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux USB-drive/SD-card/image.
The script will now ask a few questions.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
   Pop!_OS (recommended)
   Ubuntu 
   Fedora 
   Debian 
 > Arch 
arch latest selected
Which desktop environment (Desktop GUI) would you like to use?
 > Gnome (recommended)
   KDE (recommended)
   Xfce (recommended for weak devices)
   LXQt (recommended for weak devices)
   cli (no desktop environment)
   deepin 
Gnome selected
Enter a username for the new user
Username (default: 'localuser'): inderix
Using inderix as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > stable (default, recommended)
   experimental 
   mainline (recommended)
stable kernel selected
Available devices: 
Select USB-drive/SD-card name or 'image' to build an image
   sda           PSSD_T7 465.8G usb
 > image Build image instead of writing to USB/SD-card directly
Building image instead of writing directly
User input complete
Starting build
Cleaning + preparing host system
Failed to remove /tmp/depthboot-build with python, using bash
Creating mount points
umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Downloading stable 5.10 kernel
Getting kernel version
Kernel files downloaded successfully
Downloading latest arch rootfs from geo.mirror.pkgbuild.com
Downloading: 173mb / 173mb
Downloading chromeos firmware
Cloning into '/tmp/depthboot-build/firmware'...
remote: Finding sources: 100% (1404/1404)
remote: Total 1404 (delta 358), reused 1144 (delta 358)
Receiving objects: 100% (1404/1404), 94.05 MiB | 533.00 KiB/s, done.
Resolving deltas: 100% (358/358), done.
Updating files: 100% (1406/1406), done.
Preparing image
Mounting empty image
Preparing device/image partition
Flashing kernel to device/image
33488+0 records in
33488+0 records out
17145856 bytes (17 MB, 16 MiB) copied, 0.169027 s, 101 MB/s
33488+0 records in
33488+0 records out
17145856 bytes (17 MB, 16 MiB) copied, 0.207962 s, 82.4 MB/s
Formatting rootfs part
mke2fs 1.46.2 (28-Feb-2021)
Device/image preparation complete
Extracting rootfs
Extracting arch rootfs
 173MiB 0:00:05 [31.8MiB/s] [============================================>] 100%            

Rootfs extraction complete
Applying distro agnostic configuration
Extracting kernel modules
Couldn't remove non existent directory: /mnt/depthboot/lib/modules, ignoring
10.4MiB 0:00:02 [4.27MiB/s] [============================================>] 100%            
Extracting kernel headers
Couldn't remove non existent directory: /mnt/depthboot/usr/src/linux-headers-5.10.133, ignoring
9.11MiB 0:00:01 [4.96MiB/s] [============================================>] 100%            
Fixing sleep
Fixing screen rotation
Enabling resolved.conf systemd service
Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /usr/lib/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-resolved.service → /usr/lib/systemd/system/systemd-resolved.service.
Enable modules autoloading
Configuring user
/bin/sh: 1: file: not found
Traceback (most recent call last):
  File "/home/inderix/depthboot-builder/./main.py", line 143, in <module>
    build.start_build(verbose=args.verbose, local_path=args.local_path, kernel_type=user_input["kernel_type"],
  File "/home/inderix/depthboot-builder/build.py", line 461, in start_build
    post_extract(build_options, kernel_type, kernel_version, dev_release)
  File "/home/inderix/depthboot-builder/build.py", line 320, in post_extract
    host_time_zone = bash("file /etc/localtime")  # read host timezone link
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inderix/depthboot-builder/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 465, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'file /etc/localtime' returned non-zero exit status 127.
(venv) (bullseye)inderix@localhost:~/depthboot-builder$ 
```

**Comment by WeirdTreeThing** [comment]
Looks like it was able to format the drive now but file isn't installed.

**Comment by Apacelus** [comment]
@WeirdTreeThing no, it wasnt. Inderix used the image option.

Ill make an exception for the the timezone. Weird that crouton doesnt have that file tho...

**Comment by Apacelus** [comment]
Unfortunately I cannot fix the formatting issue, as it seems that that's croutons fault.

I could force the script to auto-build images on crouton, but for that I would need a reliable way to detect if its running under crouton.

**Comment by Apacelus** [comment]
locatime link issue fixed in df2f4acffe5b42e8c5e75f760ba0f52e4d306c1b
