### ISSUE TITLE
[BUG] Mount error of /dev/shm while building image

### ISSUE THREAD

**Issue by Inderix** [eupnea-linux/depthboot-builder#48]
**Describe the bug**
Image build fails due to seemingly being unable to mount /dev/shm

**Full log**
```
(venv) (bullseye)inderix@localhost:~$ git clone --depth=1 https://github.com/eupnea-linux/depthboot-builder && cd depthboot-builder && ./main.py
Cloning into 'depthboot-builder'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 53 (delta 8), reused 26 (delta 2), pack-reused 0
Receiving objects: 100% (53/53), 50.21 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (8/8), done.
Dependencies already installed, skipping
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux USB-drive/SD-card/image.
The script will now ask a few questions.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
   Pop!_OS (recommended)
   Ubuntu 
   Fedora 
   Debian 
 > Arch 
arch latest selected
Which desktop environment (Desktop GUI) would you like to use?
 > Gnome (recommended)
   KDE (recommended)
   Xfce (recommended for weak devices)
   LXQt (recommended for weak devices)
   cli (no desktop environment)
   deepin 
Gnome selected
Enter a username for the new user
Username (default: 'localuser'): inderix
Using inderix as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > stable (default, recommended)
   experimental 
   mainline (recommended)
stable kernel selected
Available devices: 
Select USB-drive/SD-card name or 'image' to build an image
   sda           PSSD_T7 465.8G usb
 > image Build image instead of writing to USB/SD-card directly
Building image instead of writing directly
User input complete
Starting build
Cleaning + preparing host system
Failed to remove /tmp/depthboot-build with python, using bash
Creating mount points
umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Downloading stable 5.10 kernel
Getting kernel version
Kernel files downloaded successfully
Downloading latest arch rootfs from geo.mirror.pkgbuild.com
Downloading: 173mb / 173mb
Downloading chromeos firmware
Cloning into '/tmp/depthboot-build/firmware'...
remote: Finding sources: 100% (1404/1404)
remote: Total 1404 (delta 358), reused 1144 (delta 358)
Receiving objects: 100% (1404/1404), 94.05 MiB | 530.00 KiB/s, done.
Resolving deltas: 100% (358/358), done.
Updating files: 100% (1406/1406), done.
Preparing image
Mounting empty image
Preparing device/image partition
Flashing kernel to device/image
33488+0 records in
33488+0 records out
17145856 bytes (17 MB, 16 MiB) copied, 0.203367 s, 84.3 MB/s
33488+0 records in
33488+0 records out
17145856 bytes (17 MB, 16 MiB) copied, 0.193502 s, 88.6 MB/s
Formatting rootfs part
mke2fs 1.46.2 (28-Feb-2021)
Device/image preparation complete
Extracting rootfs
Extracting arch rootfs
 173MiB 0:00:06 [27.2MiB/s] [============================================>] 100%            

Rootfs extraction complete
Applying distro agnostic configuration
Extracting kernel modules
Couldn't remove non existent directory: /mnt/depthboot/lib/modules, ignoring
10.4MiB 0:00:01 [6.10MiB/s] [============================================>] 100%            
Extracting kernel headers
Couldn't remove non existent directory: /mnt/depthboot/usr/src/linux-headers-5.10.133, ignoring
9.11MiB 0:00:02 [4.07MiB/s] [============================================>] 100%            
Fixing sleep
Fixing screen rotation
Enabling resolved.conf systemd service
Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /usr/lib/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-resolved.service → /usr/lib/systemd/system/systemd-resolved.service.
Enable modules autoloading
Configuring user
/bin/sh: 1: file: not found
Distro agnostic configuration complete
Configuring Arch
mount: /mnt/depthboot/dev/shm: wrong fs type, bad option, bad superblock on /dev/shm, missing codepage or helper program, or other error.
Traceback (most recent call last):
  File "/home/inderix/depthboot-builder/./main.py", line 143, in <module>
    build.start_build(verbose=args.verbose, local_path=args.local_path, kernel_type=user_input["kernel_type"],
  File "/home/inderix/depthboot-builder/build.py", line 478, in start_build
    distro.config(build_options["de_name"], build_options["distro_version"], verbose)
  File "/home/inderix/depthboot-builder/distro/arch.py", line 18, in config
    bash("mount --types tmpfs /dev/shm /mnt/depthboot/dev/shm -o rw,nosuid,nodev,relatime,inode64")
  File "/home/inderix/depthboot-builder/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 465, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mount --types tmpfs /dev/shm /mnt/depthboot/dev/shm -o rw,nosuid,nodev,relatime,inode64' returned non-zero exit status 32.
(venv) (bullseye)inderix@localhost:~/depthboot-builder$ 
```

**Build system (please complete the following information):**
 - OS: ChromeOS, Debian bullseye crouton chroot
 - Python version: 3.11

**Comment by Apacelus** [comment]
Fixed in d94e285f6aba38cf8caa650c30ef6b2d9e895c60

**Comment by Apacelus** [comment]
Unfixed in b0ae9eedaee2bb88068fb76e5f7d53a706585aa4
Commit notes:
> While this seemed like a good fix, it causes file conflicts in pacman and is generally not a good solution

**Comment by Apacelus** [comment]
It seems like we dont need to bind mount dirs for pacman at all, so perhaps a174e39ae1f866631ab59b7e7f660742283673b4 will fix it
