### ISSUE TITLE
[BUG] Build script fails after "Extracting kernel headers"

### ISSUE THREAD

**Issue by thonkinator** [eupnea-linux/depthboot-builder#50]
**Describe the bug**
After the "Extracting kernel headers" message and the download, I get an error saying `chroot: failed to run command 'bin/bash': Exec format error`

**To Reproduce**
1. Enter superuser with `su`
2. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
3. Select Arch as distro
4. Select XFCE as desktop environment
5. Select mainline
6. Select disk or image

**Full log**
```
Dependencies already installed, skipping
Verbosity increased
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux USB-drive/SD-card/image.
The script will now ask a few questions.
You can Press Ctrl+C at any time to cancel the script.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
   Pop!_OS (recommended)
   Ubuntu 
   Fedora 
 > Arch 
   Debian 
arch latest selected
Which desktop environment (Desktop GUI) would you like to use?
   Gnome (recommended)
   KDE (recommended)
 > Xfce (recommended for weak devices)
   LXQt (recommended for weak devices)
   deepin 
   budgie 
   cli 
Xfce selected
Enter a username for the new user
Username (default: 'localuser'): patrick
Using patrick as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > mainline (default, recommended)
   stable (recommended for some devices)
mainline kernel selected
Available devices: 
Select USB-drive/SD-card name or 'image' to build an image
 > sda      DataTraveler_3.0 14.4G usb
   image Build image instead of writing to USB/SD-card directly
Writing directly to sda
User input complete
Starting build
Cleaning + preparing host system
Failed to remove /tmp/depthboot-build with python, using bash

Creating mount points
umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Downloading mainline kernel
Getting kernel version
Kernel files downloaded successfully
Downloading latest arch rootfs from geo.mirror.pkgbuild.com
Downloading: 173mb / 173mb
Downloading chromeos firmware
Cloning into '/tmp/depthboot-build/firmware'...
remote: Finding sources: 100% (1406/1406)
remote: Total 1406 (delta 362), reused 1157 (delta 362)
Receiving objects: 100% (1406/1406), 95.34 MiB | 5.68 MiB/s, done.
Resolving deltas: 100% (362/362), done.
Updating files: 100% (1408/1408), done.

Preparing USB/SD-card
umount: /dev/sda: not mounted.
umount: /dev/sda1: not mounted.
umount: /dev/sda2: not mounted.
umount: /dev/sda3: not mounted.
Preparing device/image partition
/dev/sda: 8 bytes were erased at offset 0x00000200 (gpt): 45 46 49 20 50 41 52 54
/dev/sda: 8 bytes were erased at offset 0x39bfffe00 (gpt): 45 46 49 20 50 41 52 54
/dev/sda: 2 bytes were erased at offset 0x000001fe (PMBR): 55 aa






9bfb530e-87d2-4a0d-8992-54800feb2159
Flashing kernel to device/image

35480+0 records in
35480+0 records out
18165760 bytes (18 MB, 17 MiB) copied, 2.38169 s, 7.6 MB/s

35480+0 records in
35480+0 records out
18165760 bytes (18 MB, 17 MiB) copied, 3.37832 s, 5.4 MB/s

Formatting rootfs part
mke2fs 1.46.2 (28-Feb-2021)
Creating filesystem with 3751424 4k blocks and 938400 inodes
Filesystem UUID: e4ad085a-877c-4513-afe1-2a04d4b0f65d
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done   

Device/image preparation complete
Extracting rootfs
Extracting arch rootfs
/usr/bin/pv
 173MiB 0:00:26 [6.47MiB/s] [======================================================================================>] 100%            



Rootfs extraction complete
Applying distro agnostic configuration
Extracting kernel modules
Couldn't remove non existent directory: /mnt/depthboot/lib/modules, ignoring
/usr/bin/pv
10.9MiB 0:00:10 [1.02MiB/s] [======================================================================================>] 100%            

Extracting kernel headers
6.0.9
Couldn't remove non existent directory: /mnt/depthboot/usr/src/linux-headers-6.0.9, ignoring
/usr/bin/pv
26.6MiB 0:01:47 [ 252KiB/s] [======================================================================================>] 100%            

chroot: failed to run command ‘/bin/bash’: Exec format error
Traceback (most recent call last):
  File "/home/patrick/depthboot-builder/./main.py", line 153, in <module>
    build.start_build(verbose=args.verbose, local_path=args.local_path, dev_release=args.dev_build,
  File "/home/patrick/depthboot-builder/build.py", line 501, in start_build
    post_extract(build_options)
  File "/home/patrick/depthboot-builder/build.py", line 298, in post_extract
    chroot(f"ln -s /usr/src/linux-headers-{dir_kernel_version}/ /lib/modules/{dir_kernel_version}/build")
  File "/home/patrick/depthboot-builder/build.py", line 427, in chroot
    return bash(f'chroot /mnt/depthboot /bin/bash -c "{command}"')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrick/depthboot-builder/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'chroot /mnt/depthboot /bin/bash -c "ln -s /usr/src/linux-headers-6.0.9/ /lib/modules/6.0.9/build"' returned non-zero exit status 126.
Script exited unexpectedly
Run "./main.py -v" to restart with more verbose output
Run "./main.py --help" for more options
```

**Build system (please complete the following information):**
Raspberry Pi 400, 4GB ram, running Raspberry Pi OS Lite 64-bit. RPis are ARM-based, if that makes a difference

**Additional context**
I first tried running without sudo/as superuser, but I got an error saying `Command 'blkid -o value -s PARTUUID /dev/sda3' returned non-zero exit status 2.` I guess that makes sense though. After switching to sudo, I kept getting an error saying `Command 'blkid -o value -s PARTUUID /dev/sda3' returned non-zero exit status 2.`
I finally ran with `su`, which is what got me far enough to get to this issue.

**Comment by WeirdTreeThing** [comment]
Arm is unsupported. You can try using qemu user mode with binfmt but we will not help with any issues you may have.
