### ISSUE TITLE
[BUG] useradd: command not found

### ISSUE THREAD

**Issue by Evilhotdog** [eupnea-linux/depthboot-builder#53]
**Describe the bug**

Attempting to build Depthboot on Arch Linux ultimately results in not being able to find useradd within the chroot

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``

**Full log**

Verbose log:
```
Dependencies already installed, skipping
Verbosity increased
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux image.
You can Press Ctrl+C at any time to stop the script.
Select the default options if you are unsure.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
 > Pop!_OS 10.0GB (recommended)
   Ubuntu ~2.9GB
   Fedora ~1.7GB
   Arch 2.2GB
pop-os 22.04 selected
Enter a username for the new user
Username (default: 'localuser'): username
Using username as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > Mainline (default, recommended)
   ChromeOS (recommended for some devices)
Mainline kernel selected
User input complete
Not enough space in /tmp to build image. At least 13GB is required
Attempt to increase size of /tmp? (Y/n)
y
Increasing size of /tmp
Size of /tmp increased
Starting build
Cleaning + preparing host system
Creating mount points

umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Downloading mainline kernel
Downloading: 13mb / 14mb
Downloading pop-os rootfs from eupnea github releases, part 1/2
Downloading: 1811mb / 1812mb
Downloading pop-os rootfs from eupnea github releases, part 2/2
Downloading: 314mb / 315mb
Combining split pop-os rootfs, might take a while

Preparing image

Mounting empty image
/dev/loop4
Preparing device/image partition







a70369d4-7d23-4efd-830c-ed59c99d4f70
Flashing kernel to device/image

28344+0 records in
28344+0 records out
14512128 bytes (15 MB, 14 MiB) copied, 0.0693604 s, 209 MB/s

28344+0 records in
28344+0 records out
14512128 bytes (15 MB, 14 MiB) copied, 0.0652816 s, 222 MB/s

Formatting rootfs part
mke2fs 1.47.0 (5-Feb-2023)
Discarding device blocks: done                            
Creating filesystem with 2588160 4k blocks and 647168 inodes
Filesystem UUID: 6d3b6751-61d5-4dd6-a76c-10353c0e8b56
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

Device/image preparation complete
Extracting rootfs
Extracting pop-os rootfs
/usr/bin/pv
2.08GiB 0:01:40 [21.2MiB/s] [=============================================================================================================================>] 100%            


Rootfs extraction complete
Applying distro agnostic configuration

Fixing sleep
Fixing screen rotation
Copying /home/user/Sources/depthboot-builder/configs/hwdb/61-sensor.hwdb to /mnt/depthboot/etc/udev/hwdb.d/61-sensor.hwdb

Cleaning /boot
Failed to remove /mnt/depthboot/boot with python, using bash

Configuring user
/bin/bash: line 1: useradd: command not found
Traceback (most recent call last):
  File "/home/user/Sources/depthboot-builder/./main.py", line 220, in <module>
    build.start_build(verbose=args.verbose, local_path=args.local_path, dev_release=args.dev_build,
  File "/home/user/Sources/depthboot-builder/build.py", line 416, in start_build
    post_extract(build_options)
  File "/home/user/Sources/depthboot-builder/build.py", line 286, in post_extract
    chroot(f"useradd --create-home --shell /bin/bash {username}")
  File "/home/user/Sources/depthboot-builder/functions.py", line 126, in chroot
    return bash(f'chroot /mnt/depthboot /bin/bash -c "{command}"')
  File "/home/user/Sources/depthboot-builder/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'chroot /mnt/depthboot /bin/bash -c "useradd --create-home --shell /bin/bash phoebe"' returned non-zero exit status 127.
Script exited unexpectedly, please open an issue on GitHub/Discord/Revolt
Run "./main.py -v" to restart with more verbose output
Run "./main.py --help" for more options
```

**Build system (please complete the following information):**
 - OS: [e.g. Ubuntu, Windows Subsystem for Linux, Crostini(aka Linux on ChromeOS)]
 Arch Linux

**Additional context**

**Comment by Apacelus** [comment]
Fixed in b6cad03799ffb00140126d6beb6c7f3792b8f548

`git pull` and try again
