### ISSUE TITLE
[BUG] Building Pop!OS on Arch results in error processing system76-acpi-dkms

### ISSUE THREAD

**Issue by Evilhotdog** [eupnea-linux/depthboot-builder#54]
**Describe the bug**

When attempting to build Pop!OS on Arch, it fails after trying to run apt when trying to install system76-acpi-dkms
**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py``
2. Select Pop!OS as distro, on Arch

**Full log**

Verbose log:
```
Dependencies already installed, skipping
Verbosity increased
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux image.
You can Press Ctrl+C at any time to stop the script.
Select the default options if you are unsure.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
 > Pop!_OS 0.0GB (recommended)
   Ubuntu ~2.9GB
   Fedora ~1.7GB
   Arch 2.2GB
pop-os 22.04 selected
Enter a username for the new user
Username (default: 'localuser'): phoebe
Using phoebe as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > Mainline (default, recommended)
   ChromeOS (recommended for some devices)
Mainline kernel selected
User input complete
Not enough space in /tmp to build image. At least 13GB is required
Attempt to increase size of /tmp? (Y/n)
y
Increasing size of /tmp
Size of /tmp increased
Starting build
Cleaning + preparing host system
Creating mount points

umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Downloading mainline kernel
Downloading: 13mb / 14mb
Downloading pop-os rootfs from eupnea github releases, part 1/2
Downloading: 1811mb / 1812mb
Downloading pop-os rootfs from eupnea github releases, part 2/2
Downloading: 314mb / 315mb
Combining split pop-os rootfs, might take a while

Preparing image

Mounting empty image
/dev/loop1
Preparing device/image partition







ebdfac5b-6f4a-4dcc-9d6f-490e2040c63a
Flashing kernel to device/image

28344+0 records in
28344+0 records out
14512128 bytes (15 MB, 14 MiB) copied, 0.064367 s, 225 MB/s

28344+0 records in
28344+0 records out
14512128 bytes (15 MB, 14 MiB) copied, 0.0641801 s, 226 MB/s

Formatting rootfs part
mke2fs 1.47.0 (5-Feb-2023)
Discarding device blocks: done                            
Creating filesystem with 2588160 4k blocks and 647168 inodes
Filesystem UUID: 4f52f575-574a-4647-a4cc-63a78f6b05c3
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

Device/image preparation complete
Extracting rootfs
Extracting pop-os rootfs
/usr/bin/pv
2.08GiB 0:01:38 [21.6MiB/s] [================================>] 100%            


Rootfs extraction complete
Applying distro agnostic configuration

Fixing sleep
Fixing screen rotation
Copying /home/alice/Sources/depthboot-builder/configs/hwdb/61-sensor.hwdb to /mnt/depthboot/etc/udev/hwdb.d/61-sensor.hwdb

Cleaning /boot
Failed to remove /mnt/depthboot/boot with python, using bash

Configuring user



/etc/localtime: symbolic link to /usr/share/zoneinfo/Europe/London

Distro agnostic configuration complete
Configuring Pop!_OS
Removing casper debs
E: Cannot write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
invoke-rc.d: could not determine current runlevel
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED
  btrfs-progs* casper* cifs-utils* distinst* distinst-v2* dmraid* efibootmgr*
  expect* f2fs-tools* fatresize* gettext* gparted* gparted-common*
  grub-common* grub2-common* kernelstub* kpartx* kpartx-boot* libdistinst*
  libdmraid1.0.0.rc16* libinih1* libnss-mymachines* localechooser-data*
  os-prober* pop-installer* pop-installer-casper* pop-shop-casper*
  squashfs-tools* systemd-container* tcl-expect* user-setup* xfsprogs*
0 to upgrade, 0 to newly install, 32 to remove and 0 not to upgrade.
After this operation, 51.5 MB disk space will be freed.
(Reading database ... 238723 files and directories currently installed.)
Removing pop-installer (0.0.1~1667340702~22.04~f4d8514) ...
Removing distinst-v2 (0.1.0~1654884333~22.04~0cf6b13) ...
Removing distinst (0.3.2~1674238609~22.04~a5bdb0c) ...
Removing libdistinst (0.3.2~1674238609~22.04~a5bdb0c) ...
Removing btrfs-progs (5.16.2-1) ...
Removing pop-installer-casper (0.0.1~1667340702~22.04~f4d8514) ...
Removing pop-shop-casper (3.4.2pop0~1666654031~22.04~de9193e) ...
Removing casper (1.470.2) ...
Removing cifs-utils (2:6.14-1ubuntu0.1) ...
Removing dmraid (1.0.0.rc16-10ubuntu2) ...
update-initramfs: deferring update (trigger activated)
Removing kernelstub (3.1.4~1674849051~22.04~851230b) ...
Removing efibootmgr (17-1ubuntu2) ...
Removing expect (5.45.4-2build1) ...
Removing f2fs-tools (1.14.0-2build1) ...
Removing fatresize (1.1.0-1) ...
Removing gettext (0.21-4ubuntu4) ...
Removing gparted (1.3.1-1ubuntu1) ...
Removing gparted-common (1.3.1-1ubuntu1) ...
Removing grub2-common (2.06-2ubuntu7.1) ...
Removing os-prober (1.79ubuntu2) ...
Removing grub-common (2.06-2ubuntu7.1) ...
Removing kpartx-boot (0.8.8-1ubuntu1.22.04.1) ...
update-initramfs: deferring update (trigger activated)
Removing kpartx (0.8.8-1ubuntu1.22.04.1) ...
Removing libdmraid1.0.0.rc16:amd64 (1.0.0.rc16-10ubuntu2) ...
Removing xfsprogs (5.13.0-1ubuntu2) ...
Removing libinih1:amd64 (53-1ubuntu3) ...
Removing libnss-mymachines:amd64 (249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb) ...
Checking NSS setup...
Removing localechooser-data (2.89ubuntu3) ...
Removing squashfs-tools (1:4.5-3build1) ...
Removing systemd-container (249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb) ...
Removing tcl-expect:amd64 (5.45.4-2build1) ...
Removing user-setup (1.88ubuntu1) ...
Processing triggers for initramfs-tools (0.140ubuntu13.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
Processing triggers for dbus-broker (29-4build1) ...
Processing triggers for install-info (6.8-4build1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
(Reading database ... 237664 files and directories currently installed.)
Purging configuration files for kpartx-boot (0.8.8-1ubuntu1.22.04.1) ...
Purging configuration files for grub2-common (2.06-2ubuntu7.1) ...
Purging configuration files for cifs-utils (2:6.14-1ubuntu0.1) ...
Purging configuration files for distinst-v2 (0.1.0~1654884333~22.04~0cf6b13) ...
Purging configuration files for casper (1.470.2) ...
Purging configuration files for grub-common (2.06-2ubuntu7.1) ...
Purging configuration files for libnss-mymachines:amd64 (249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb) ...
Purging configuration files for dmraid (1.0.0.rc16-10ubuntu2) ...
update-initramfs: deferring update (trigger activated)
Purging configuration files for systemd-container (249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb) ...
Purging configuration files for user-setup (1.88ubuntu1) ...
Purging configuration files for kernelstub (3.1.4~1674849051~22.04~851230b) ...
Processing triggers for initramfs-tools (0.140ubuntu13.1) ...
Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Get:2 https://eupnea-linux.github.io/apt-repo/debian_ubuntu jammy InRelease [2,438 B]
Get:3 http://apt.pop-os.org/release jammy InRelease [16.6 kB]
Get:4 https://eupnea-linux.github.io/apt-repo/debian_ubuntu jammy/main amd64 Packages [1,936 B]
Hit:5 http://apt.pop-os.org/ubuntu jammy InRelease
Get:6 http://apt.pop-os.org/ubuntu jammy-security InRelease [110 kB]
Get:7 http://apt.pop-os.org/ubuntu jammy-updates InRelease [119 kB]
Get:8 http://apt.pop-os.org/ubuntu jammy-backports InRelease [107 kB]
Get:9 http://apt.pop-os.org/release jammy/main Sources [86.0 kB]
Get:10 http://apt.pop-os.org/release jammy/main amd64 Packages [196 kB]
Get:11 http://apt.pop-os.org/release jammy/main i386 Packages [84.2 kB]
Get:12 http://apt.pop-os.org/release jammy/main amd64 DEP-11 Metadata [43.4 kB]
Get:13 http://apt.pop-os.org/ubuntu jammy/main Translation-en_GB [483 kB]
Get:14 http://apt.pop-os.org/ubuntu jammy/restricted Translation-en_GB [5,768 B]
Get:15 http://apt.pop-os.org/ubuntu jammy/universe Translation-en_GB [838 kB]
Get:16 http://apt.pop-os.org/ubuntu jammy/multiverse Translation-en_GB [102 kB]
Get:17 http://apt.pop-os.org/ubuntu jammy-security/main Sources [160 kB]
Get:18 http://apt.pop-os.org/ubuntu jammy-security/main amd64 Packages [682 kB]
Get:19 http://apt.pop-os.org/ubuntu jammy-security/main i386 Packages [266 kB]
Get:20 http://apt.pop-os.org/ubuntu jammy-security/main Translation-en [139 kB]
Get:21 http://apt.pop-os.org/ubuntu jammy-security/main amd64 DEP-11 Metadata [41.4 kB]
Get:22 http://apt.pop-os.org/ubuntu jammy-security/main amd64 c-n-f Metadata [8,544 B]
Get:23 http://apt.pop-os.org/ubuntu jammy-security/universe i386 Packages [512 kB]
Get:24 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 Packages [696 kB]
Get:25 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 DEP-11 Metadata [17.1 kB]
Get:26 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 c-n-f Metadata [13.5 kB]
Get:27 http://apt.pop-os.org/ubuntu jammy-updates/universe Sources [210 kB]
Get:28 http://apt.pop-os.org/ubuntu jammy-updates/main Sources [363 kB]
Get:29 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages [941 kB]
Get:30 http://apt.pop-os.org/ubuntu jammy-updates/main i386 Packages [455 kB]
Get:31 http://apt.pop-os.org/ubuntu jammy-updates/main Translation-en [203 kB]
Get:32 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 DEP-11 Metadata [101 kB]
Get:33 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 c-n-f Metadata [13.6 kB]
Get:34 http://apt.pop-os.org/ubuntu jammy-updates/universe i386 Packages [601 kB]
Get:35 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages [879 kB]
Get:36 http://apt.pop-os.org/ubuntu jammy-updates/universe Translation-en [173 kB]
Get:37 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [269 kB]
Get:38 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 c-n-f Metadata [17.9 kB]
Get:39 http://apt.pop-os.org/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:40 http://apt.pop-os.org/ubuntu jammy-backports/main amd64 DEP-11 Metadata [7,980 B]
Get:41 http://apt.pop-os.org/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [12.4 kB]
Fetched 8,979 kB in 7s (1,374 kB/s)
Reading package lists...
E: Cannot write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
invoke-rc.d: could not determine current runlevel
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
/usr/sbin/dkms: line 2117: /dev/fd/63: No such file or directory
/usr/sbin/dkms: line 2048: /dev/fd/63: No such file or directory
Loading new system76_acpi-1.0.2~1678132042~22.04~ed01124 DKMS files...
grep: /proc/cpuinfo: No such file or directory
It is likely that 6.2.2-arch1-1 belongs to a chroot's host
Building for 6.0.12-76060006-generic and 6.1.11-76060111-generic
/usr/sbin/dkms: line 2117: /dev/fd/63: No such file or directory
/usr/sbin/dkms: line 2048: /dev/fd/63: No such file or directory
dpkg: error processing package system76-acpi-dkms (--configure):
 installed system76-acpi-dkms package post-installation script subprocess returned error exit status 1
/bin/df: cannot read table of mounted file systems: No such file or directory
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Errors were encountered while processing:
 system76-acpi-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
Traceback (most recent call last):
  File "/home/alice/Sources/depthboot-builder/./main.py", line 225, in <module>
    build.start_build(verbose=args.verbose, verbose_kernel=args.verbose_kernel, local_path=args.local_path,
  File "/home/alice/Sources/depthboot-builder/build.py", line 430, in start_build
    distro.config(build_options["de_name"], build_options["distro_version"], verbose, build_options["kernel_type"])
  File "/home/alice/Sources/depthboot-builder/distro/pop_os.py", line 24, in config
    chroot("apt-get upgrade -y")
  File "/home/alice/Sources/depthboot-builder/functions.py", line 126, in chroot
    return bash(f'chroot /mnt/depthboot /bin/bash -c "{command}"')
  File "/home/alice/Sources/depthboot-builder/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'chroot /mnt/depthboot /bin/bash -c "apt-get upgrade -y"' returned non-zero exit status 100.
Script exited unexpectedly, please open an issue on GitHub/Discord/Revolt
Run "./main.py -v" to restart with more verbose output
Run "./main.py --help" for more options
```

**Build system (please complete the following information):**
 - OS: Arch Linux

**Comment by Apacelus** [comment]
Same as in todays rootfs repacker workflow https://github.com/eupnea-linux/pop-os-rootfs/actions/runs/4349741259/jobs/7599742610#step:4:971

**Comment by Apacelus** [comment]
Gonna wait a few days to see if this gets resolved upstream, otherwise Ill work with dpkg like [here](https://github.com/eupnea-linux/depthboot-builder/blob/main/distro/ubuntu.py#L49-L63)

**Comment by Apacelus** [comment]
Dpkg solution didnt really work... I suggest you help me in asking the PopOS devs to update their iso in their [mattermost chat](https://chat.pop-os.org/)

**Comment by Apacelus** [comment]
Alright, System76 just released a new iso, so building PopOS should work now

**Comment by ChocolateLoverRaj** [comment]
@Apacelus i just tried installing it today and i got an error. I think it was the same error. I will try to re-run it with `-v`, but my Chromebook is out of space. (I think some space was reserved by `main.py` but idk how to remove it). Do you have any suggestions? Also, would selecting something other than pop os work?

**Comment by Apacelus** [comment]
Were you building on a fresh git clone there?

**Comment by Apacelus** [comment]
Doesnt happen on my Fedora desktop. Also, the space that was "reserved" by main.py was just remounting /tmp. So a reboot would "fix" that

**Comment by Apacelus** [comment]
There was an issue with building ubuntu-based distros the past ~12 hours, but that was not related to the builder system and was not system76 packages

**Comment by ChocolateLoverRaj** [comment]
Should I try again today? Should I wait until tomorrow to try it again?

**Comment by Apacelus** [comment]
You can try again now, I fixed the kernel packages issue already
