### ISSUE TITLE
Script fails to fetch file for Ubuntu

### ISSUE THREAD

**Issue by C-Stew** [eupnea-linux/depthboot-builder#71]
**Describe the bug**
Attempting to run ./main.py to create a bootable image fails with any parameters.

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/depthboot-builder && cd depthboot-builder && ./main.py -v``
2. Select Ubuntu 22.04 (LTS) as distro
3. Select Xfce as desktop environment
4. Kernel selection doesn't change outcome

**Full log**

Verbose log:
```
Verbosity increased
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux image.
You can press Ctrl+C at any time to stop the script.
Select the default options if you are unsure.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
   Fedora ~2.4GB (recommended)
 > Ubuntu ~3.8GB
   Pop!_OS 8.2GB
   Linux Mint (Cinnamon edition) 7.0GB
   Arch 3.0GB
   Generic ISO (NOT recommended)
Which Ubuntu version would you like to use?
   23.04 3.8GB (latest, recommended)
 > 22.04 3.7GB (LTS version)
ubuntu 22.04 selected
Which desktop environment (Desktop GUI) would you like to use?
   Gnome (recommended) +5.4GB
   KDE (recommended) +5.3GB
 > Xfce (recommended for weak devices) +5.1GB
   LXQt (recommended for weak devices) +4.7GB
   Cinnamon +7.0GB
   deepin +7.7GB
   budgie +5.7GB
   cli +0GB
Xfce selected
Enter a username for the new user
Username (default: 'localuser'): localuser
Using localuser as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
 > Mainline (default, recommended)
   ChromeOS (recommended for some devices)
Mainline kernel selected
User input complete
Removing old depthboot build files
umount: /tmp/depthboot-build/bzImage: not mounted
umount: /tmp/depthboot-build/bzImage.signed: not mounted
umount: /tmp/depthboot-build/ubuntu-rootfs.tar.xz: not mounted
Unmounting old depthboot mounts if present
umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Namespace(local_path=None, device_override=None, device_selection=False, verbose=True, no_shrink=False, verbose_kernel=False, skip_size_check=False, image_size=[10], dev_build=False, skip_commit_check=False)
Starting build
Creating temporary build directory + mount point
Downloading mainline kernel
Downloading: 27mb / 28mb
Downloading ubuntu rootfs, version 22.04 from eupnea github releases
Downloading: 161mb / 161mb
Preparing image

Mounting empty image
/dev/loop36
Preparing device/image partition







3f9a5ee7-6a25-45ca-9516-587e24e4e1d8
Rootfs partition UUID: 3f9a5ee7-6a25-45ca-9516-587e24e4e1d8
Flashing kernel to device/image

56712+0 records in
56712+0 records out
29036544 bytes (29 MB, 28 MiB) copied, 0.396158 s, 73.3 MB/s

56712+0 records in
56712+0 records out
29036544 bytes (29 MB, 28 MiB) copied, 0.403708 s, 71.9 MB/s

Formatting rootfs part
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks: done                            
Creating filesystem with 2588160 4k blocks and 647168 inodes
Filesystem UUID: 277e401e-d26a-414b-be89-427f2c264f0f
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

Device/image preparation complete
Extracting rootfs
Extracting ubuntu rootfs
 161MiB 0:00:13 [12.0MiB/s] [========================================================>] 100%            


Rootfs extraction complete
Applying distro agnostic configuration



Fixing screen rotation
Copying /home/thec_stew/depthboot-builder/configs/hwdb/61-sensor.hwdb to /mnt/depthboot/etc/udev/hwdb.d/61-sensor.hwdb

Cleaning /boot
Configuring user



/etc/localtime: symbolic link to /usr/share/zoneinfo/America/Indiana/Indianapolis

Distro agnostic configuration complete
Configuring Ubuntu
Installing dependencies
Get:1 https://eupnea-linux.github.io/apt-repo/debian_ubuntu jammy InRelease [2438 B]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:4 https://eupnea-linux.github.io/apt-repo/debian_ubuntu jammy/main amd64 Packages [2419 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [800 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main Translation-en [510 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [156 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [830 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/restricted Translation-en [18.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/universe Translation-en [5652 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [131 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [729 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [121 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [34.3 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [6464 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy/multiverse Translation-en [112 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [40.9 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [10.2 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [22.2 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [15.0 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1069 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [221 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [873 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [137 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [912 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [183 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [39.0 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [8736 B]
Fetched 13.0 MB in 4s (3393 kB/s)
Reading package lists...
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.13%2bdfsg-1ubuntu0.3_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:b455050153c63f2461122b1775d596501796f3f5e4718e984ec42640acdc031188fb5b778e5858e4bb8c3f4ac0617fcc8dc65249c71a8b57f13184552e72b1a4
    - SHA256:00fc64c74b41d84ab6c61f9f68d22656525f2748d763a9d3729f8ec555af53e4
    - SHA1:de2f1e072c2b4f92bddd732dcb7b008e9eabe491 [weak]
    - MD5Sum:728b08e5bf9eb2c5571611af33dd6d8e [weak]
    - Filesize:762606 [weak]
   Hashes of received file:
    - SHA512:b0661274690a610145091f607104eaa2fca97fc59dd4780321ddd4396d6562cdea4f5b91749f5f17bf3656cedb9d347bc3001f53a032456509283261baa7eda2
    - SHA256:8cc2cbefe6713ba8a4f362aa3dbf18105141bbcbd590509f36246c79ae5bc5ee
    - SHA1:2545da2256ec516295488091849e3a746b1806d7 [weak]
    - MD5Sum:0a1a2b5722f9195686c81b1be3ccef44 [weak]
    - Filesize:762606 [weak]
   Last modification reported: Wed, 19 Apr 2023 15:03:48 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Traceback (most recent call last):
  File "/home/thec_stew/depthboot-builder/./main.py", line 303, in <module>
    build.start_build(build_options=user_input, args=args)
  File "/home/thec_stew/depthboot-builder/build.py", line 529, in start_build
    distro.config(build_options["de_name"], build_options["distro_version"], args.verbose, build_options["kernel_type"])
  File "/home/thec_stew/depthboot-builder/distro/ubuntu.py", line 39, in config
    chroot("apt-get upgrade -y")
  File "/home/thec_stew/depthboot-builder/functions.py", line 124, in chroot
    return bash(f'chroot /mnt/depthboot /bin/bash -c "{command}"')
  File "/home/thec_stew/depthboot-builder/functions.py", line 117, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'chroot /mnt/depthboot /bin/bash -c "apt-get upgrade -y"' returned non-zero exit status 100.
Script exited unexpectedly, please open an issue on GitHub/Discord/Revolt
Run "./main.py -v" to restart with more verbose output
Run "./main.py --help" for more options
```

**Build system (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS

**Additional context**
I have tried using different selections, such as Ubuntu 23, LXQt, or ChromeOS Kernel, with this happening each time.

**Comment by Apacelus** [comment]
Not an issue with the script. Ill let the rootfs rebuild, but I suspect its some server side error (ubuntu repos, not ours)
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.13%2bdfsg-1ubuntu0.3_amd64.deb Hash Sum mismatch
Hashes of expected file:
- SHA512:b455050153c63f2461122b1775d596501796f3f5e4718e984ec42640acdc031188fb5b778e5858e4bb8c3f4ac0617fcc8dc65249c71a8b57f13184552e72b1a4
- SHA256:00fc64c74b41d84ab6c61f9f68d22656525f2748d763a9d3729f8ec555af53e4
- SHA1:de2f1e072c2b4f92bddd732dcb7b008e9eabe491 [weak]
- MD5Sum:728b08e5bf9eb2c5571611af33dd6d8e [weak]
- Filesize:762606 [weak]
Hashes of received file:
- SHA512:b0661274690a610145091f607104eaa2fca97fc59dd4780321ddd4396d6562cdea4f5b91749f5f17bf3656cedb9d347bc3001f53a032456509283261baa7eda2
- SHA256:8cc2cbefe6713ba8a4f362aa3dbf18105141bbcbd590509f36246c79ae5bc5ee
- SHA1:2545da2256ec516295488091849e3a746b1806d7 [weak]
- MD5Sum:0a1a2b5722f9195686c81b1be3ccef44 [weak]
- Filesize:762606 [weak]
Last modification reported: Wed, 19 Apr 2023 15:03:48 +0000
```

**Comment by C-Stew** [comment]
Same thing happened again, this time with different hashes received.
```Reading package lists...
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.13%2bdfsg-1ubuntu0.3_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:b455050153c63f2461122b1775d596501796f3f5e4718e984ec42640acdc031188fb5b778e5858e4bb8c3f4ac0617fcc8dc65249c71a8b57f13184552e72b1a4
    - SHA256:00fc64c74b41d84ab6c61f9f68d22656525f2748d763a9d3729f8ec555af53e4
    - SHA1:de2f1e072c2b4f92bddd732dcb7b008e9eabe491 [weak]
    - MD5Sum:728b08e5bf9eb2c5571611af33dd6d8e [weak]
    - Filesize:762606 [weak]
   Hashes of received file:
    - SHA512:9edc49cb13a7127884f6b6b451eedd8c54991e04b6caf4a57d0850719bde1dca99e1c1f2e32832ecc669f164880572d41f7aa32307e45ba6e0b2ddabdf49ccf1
    - SHA256:75d4be83da65ad3b5e04cba514653265e06f2d4d6ea70fd5f7aabbc5ac539322
    - SHA1:5f998c31fbb7492b7d0d9ed4bfc6a7c2215be284 [weak]
    - MD5Sum:82a7312c5b78231b232ae520f0a00ab7 [weak]
    - Filesize:762606 [weak]
   Last modification reported: Wed, 19 Apr 2023 15:03:48 +0000
```

**Comment by Apacelus** [comment]
Actually I just tried myself too and neither I nor the github containers have any issues. Are you sure your network is not blocking the ubuntu repos?

**Comment by C-Stew** [comment]
This is possible, as I do use Cloudflare's VPN. I have school now, and will be able to try again after 4PM ET.

**Comment by C-Stew** [comment]
It keeps failing on different files, but the interesting thing is that the checksums of the files the script downloads are correct when I download them and check them with https://emn178.github.io/online-tools/sha512_file_hash.html.
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/packagekit/packagekit-tools_1.2.5-2ubuntu2_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:5a662ae653d1639e83a3683a9a6938e2eb5d6d54efec2f369d7404c696223bd2be3107d31a8f06ddeb05a33e9fe3b12814029f00edde5eb081622b7023a2f18e
    - SHA256:ed5745757bc005dfdfbfdb2b9d01485cb320438884a4ba6fe93db8d1f3325214
    - SHA1:dba083cdb8386a442ec019edbd366d71dc3e2ac3 [weak]
    - MD5Sum:e51803f23dc9c8797342b9126dd2d30c [weak]
    - Filesize:28772 [weak]
   Hashes of received file:
    - SHA512:be77207a72fe5fed80d47eebc42fb8cf2cb4629b13caf674c2b1f9f853b3b63befc6eba196cd2d4df743705505fa041e895853cd1b8f017b5f0c62d8ebeede89
    - SHA256:e9b6cdefd78cfe98ecdfb9d442ab0f4a56e55fcde876e8c7bd4c22d516b76be7
    - SHA1:714d16bc6fa2c0f12170604ebc1a2e3570f8ebaf [weak]
    - MD5Sum:bd93af472db6c037b94478f9a1cd6ab1 [weak]
    - Filesize:28772 [weak]
   Last modification reported: Mon, 14 Mar 2022 19:48:56 +0000

```
![image](https://user-images.githubusercontent.com/51380437/235924699-ee3db1f4-2040-4bd8-9f57-7178190d6b69.png)

I'm using Python 3.10.6 if that has any relevance.

**Comment by C-Stew** [comment]
Cloudflare VPN seemed to be the issue. I disabled it and it now reaches `Installing Xfce` without issues.
