### ISSUE TITLE
[BUG] PopOS will not build because of a false "no space left on device" error

### ISSUE THREAD

**Issue by cornflakes6374** [eupnea-linux/depthboot-builder#82]
**Describe the bug**
When building PopOS on a chromebook running crouton, it shows a "cat: no space left on device error". Build Device (not external media device) has 17GB of internal storage

**To Reproduce**
1. Run ``git clone --depth=1 https://github.com/eupnea-linux/eupnea-builder; cd eupnea-builder; ./main.py (option to also run --skip-size-check)``
2. Select PopOS as distro
3. Select (forced chosen de due to distro) as desktop environment
4. build

**Full log**

Verbose log:
```
Verbosity increased
Welcome to Depthboot, formerly known as Breath
This script will create a bootable Linux image.
You can press Ctrl+C at any time to stop the script.
Select the default options if you are unsure.
Press Enter to continue...
Which Linux distribution (flavor) would you like to use?
   Fedora ~2.5GB (recommended)
   Ubuntu ~3.8GB
 > Pop!_OS 8.2GB
   Linux Mint (Cinnamon edition) 7.0GB
   Arch 3.1GB
   Generic ISO (NOT recommended)
pop-os 22.04 selected
Enter a username for the new user
Username (default: 'localuser'): corn
Using corn as username
Please set a secure password
Password: 
Repeat password: 
Password set
Which kernel type would you like to use? Usually there is no need to change this
   ChromeOS (default, recommended for older devices)
 > Mainline (newer kernel, recommended)
Mainline kernel selected
User input complete
Removing old depthboot build files
umount: /tmp/depthboot-build/pop-os-rootfs.split.aa: not mounted
umount: /tmp/depthboot-build/pop-os-rootfs.tar.xz: not mounted
Unmounting old depthboot mounts if present
umount: /mnt/depthboot: not mounted.
Failed to unmount /mnt/depthboot, ignore
Namespace(local_path=None, device_override=None, device_selection=False, verbose=True, no_shrink=False, no_deps_check=False, verbose_kernel=False, skip_size_check=True, image_size=[10], dev_build=False, skip_commit_check=False)
Starting build
Creating temporary build directory + mount point
Downloading pop-os rootfs from eupnea github releases
Downloading: 1765mb / 1766mb
Combining split pop-os rootfs, might take a while
cat: /tmp/depthboot-build/pop-os-rootfs.split.aa: No space left on device
Traceback (most recent call last):
  File "/home/corn/depthboot-builder/./main.py", line 311, in <module>
    build.start_build(build_options=user_input, args=args)
  File "/home/corn/depthboot-builder/build.py", line 478, in start_build
    download_rootfs(build_options["distro_name"], build_options["distro_version"])
  File "/home/corn/depthboot-builder/build.py", line 66, in download_rootfs
    bash("cat /tmp/depthboot-build/pop-os-rootfs.split.?? > /tmp/depthboot-build/pop-os-rootfs.tar.xz")
  File "/home/corn/depthboot-builder/functions.py", line 117, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cat /tmp/depthboot-build/pop-os-rootfs.split.?? > /tmp/depthboot-build/pop-os-rootfs.tar.xz' returned non-zero exit status 1.
Script exited unexpectedly, please open an issue on GitHub/Discord/Revolt
Run "./main.py -v" to restart with more verbose output
Run "./main.py --help" for more options
(bookworm)corn@localhost:~/depthboot-builder$

```
Output of df -h (look at the 1st top entry)
```
(bookworm)corn@localhost:~/depthboot-builder$ df -h
Filesystem                                  Size  Used Avail Use% Mounted on
/dev/mmcblk0p1                               21G  2.7G   17G  14% /
devtmpfs                                    1.9G     0  1.9G   0% /dev
tmpfs                                       1.9G   77M  1.8G   5% /dev/shm
tmpfs                                       1.9G  1.9G     0 100% /tmp
tmpfs                                       381M  8.0K  381M   1% /run
tmpfs                                       5.0M     0  5.0M   0% /run/lock
tmpfs                                       1.9G  752K  1.9G   1% /var/host/dbus
/dev/mapper/encstateful                     6.0G  761M  5.2G  13% /var/host/timezone
/dev/root                                   2.8G  2.4G  398M  86% /usr/lib/modules/4.14.311-20313-g5a3b4037ba14
media                                       1.9G     0  1.9G   0% /var/host/media
fusebox://fusebox                           1.0T     0  1.0T   0% /var/host/media/fuse/fusebox
drivefs://C7F709C9B049CC0F8629BB596E58FA45  1.0E  7.1G  1.0E   1% /var/host/media/fuse/drivefs-8da365fe401d44375a0e8a28218fc69a
/dev/sda3                                    30G   16K   30G   1% /var/host/media/removable/UNTITLED
none                                        1.9G     0  1.9G   0% /sys/fs/cgroup
none                                        1.9G  4.0K  1.9G   1% /sys/fs/selinux
(bookworm)corn@localhost:~/depthboot-builder$ 

```
**Build system (please complete the following information):**
 - OS: [e.g. Ubuntu, Windows Subsystem for Linux, Crostini(aka Linux on ChromeOS)]
Crouton running on ChromeOS 113 in Samsung chromebook 4 (casta)
**Additional context**
none

**Comment by cornflakes6374** [comment]
running without the --skip-size-check paramater causes my chromebook to freeze in a black screen with the cursor still there, then it goes back to the desktop.

**Comment by ChocolateLoverRaj** [comment]
> running without the --skip-size-check paramater causes my chromebook to freeze in a black screen with the cursor still there, then it goes back to the desktop.

Last time I tried Pop!_OS (without `--skip-size-check`) I got a grayish-blue screen after logging in. Does the same thing happen to you?

**Comment by cornflakes6374** [comment]
havent built the image yet, so it might be an issue with the graphics drivers.
